urls.py
from django.urls import include, path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'djangoTask'
urlpatterns = [
    path('', views.index, name='index'),
    path('index/<str:message>', views.index, name='indexM'),
    path('about', views.about, name='about'),
    path('base', views.base, name='base'),
    path('import', views.importData, name='import'),
    path('export', views.exportData, name='export'),
    path('<int:todo_id>/status/', views.status, name='status'),
    path('<int:todo_id>/', views.detailViewNonGeneric, name='detail'),
    path('<int:todo_id>/editPost/', views.editPost, name='editPost'),
    path('delete/', views.deletePost, name='delete'),
    path('createPost', views.editPost, name='createPost'),
    path('new',views.detailViewNonGeneric,name='new'),
    path('accounts/', include('django.contrib.auth.urls')),
]

apiPatterns = [
    path('api/', views.todoList.as_view(), name='api'),
    path('api/<int:pk>/', views.todoDetail.as_view(), name='apiIdx'),
    path('api/users/',views.UserList.as_view()),
    path('api/users/<int:pk>/',views.UserDetail.as_view()),
]
apiPatterns=format_suffix_patterns(apiPatterns)
urlpatterns = urlpatterns+apiPatterns
urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
]

templates/djangoTask/about.html
{% extends "djangoTask/base.html"  %}
{% block title %}About{% endblock %}
{% block navActive %}"about"{% endblock %}
{% block content %}
<div class="container-content">
  <div class="container-fluid">
    <h1>About</h1>
  </div>

  <div class="container-fluid">
    <strong><i>djangoTask</i></strong> is a task ("<i>todo</i>") tracker application that I'm building as
      a learning project for the django framework.
  </div>

  <div class="container-fluid">
      Source code can be found at <a href="https://github.com/DJTakushi/djangoTask">https://github.com/DJTakushi/djangoTask</a>.
      <br>
      Notable libraries/tools include:
      <ul>
      <li><a href="https://www.djangoproject.com/">Django</a></li>
      <li><a href="https://getbootstrap.com/docs/3.4/css/">Bootstrap</a></li>
      <li><a href="https://marcbruederlin.github.io/particles.js/">Particle.js</a></li>
      <li><a href="https://whitenoise.evans.io/en/stable/index.html">WhiteNoise</a></li>
      </ul>
  </div>
</div>
{% endblock %}

templates/djangoTask/base.html
<!doctype html>
<html lang="en" class="theme-light">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}BASE TEMPLATE{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'djangoTask/style.css' %}">
  <script src="{% static 'djangoTask/takushi.js' %}"></script>
  <link rel="icon" type="image/x-icon" href="{% static 'djangoTask/images/favicon.ico' %}">

</head>

<body>
  <div class="cover-container d-flex h-100 p-3 mx-auto flex-column containerParticle t_overflow">
    <nav class="navbar navbar-expand">
      <a class="navbar-brand nav-link index" href="{% url 'djangoTask:index' %}" id="index">Todo</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item" id="new">
            <a class="nav-link" href="{% url 'djangoTask:new' %}" id="new">New</a>
          </li>
          <li class="nav-item" id="import">
            <a class="nav-link" href="{% url 'djangoTask:import' %}" id="import">Import</a>
          </li>
          <li class="nav-item" id="export">
            <a class="nav-link" href="{% url 'djangoTask:export' %}" id="export">Export</a>
          </li>
        </ul>
      </div>
      <a class="btn btn-primary btn-sm" id="switch" onclick="toggleTheme()">Theme</a>
      <ul class="navbar-nav">
        <!-- <li class="nav-item">
        </li> -->
        <li class="nav-item">
          <a class="nav-link tNav" href="{% url 'takushiIndex' %}" id="takushi">takushi</a>
        </li>
        <li class="nav-item">
          <a class="nav-link tNav" href="{% url 'djangoTask:about' %}" id="about">About</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link tNav" href="{% url 'usersView' %}" id="users">Users</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link tNav dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
            <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'usersView' %}">Users</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link tNav" href="{% url 'login' %}" id="user">login</a>
        </li>
        {% endif %}
      </ul>
    </nav>
      {% block content %}
      <div class="container-content">
      <p>Base class template that is extended for other templates</p>
      </div>
      {% endblock %}
  </div>
  <canvas class="background"></canvas>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/particlesjs/2.2.2/particles.min.js"></script>
  <script>
    setActiveNavLink({% block navActive %}"base"{% endblock %})
  </script>
</body>

</html>

templates/djangoTask/blank.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Todo Index</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'djangoTask/style.css' %}">
</head>

<body>
  <div class="cover-container d-flex h-100 p-3 mx-auto flex-column containerParticle">
    <nav class="navbar navbar-expand navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'djangoTask:new' %}">New</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'djangoTask:blank' %}">Blank</a>
          </li>
        </ul>
      </div>
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'djangoTask:about' %}">About</a>
        </li>
      </ul>
    </nav>
  </div>


  <canvas class="background"></canvas>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/particlesjs/2.2.2/particles.min.js"></script>
  <script src="{% static 'djangoTask/takushi.js' %}"></script>
</body>

</html>

templates/djangoTask/detailNonGeneric.html
{% extends "djangoTask/base.html"  %}
{% block title %}Details - {{ todo_title }} {% endblock %}
{% block content %}
<div class="container-content">
  <div class="container-fluid">
    <h1>{{ todo_title }}</h1>
  </div>

  <div class="container-fluid">
    {% if todo_id %}
    <form action="{% url 'djangoTask:editPost' todo_id %}" method="post">
      {% else %}
      <form action="{% url 'djangoTask:createPost' %}" method="post">
        {% endif %}

        {% csrf_token %}
        <fieldset>
          {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

          <table class="table table-striped table-hover table-sm">
            <caption>todo fields</caption>
            <tr>
              <td>ID</td>
              <td>{{todo_id}}</td>
            </tr>
            <tr>
              <td>Title</td>
              <td><input type="text" name="title" id="title" value="{{ todo_title }}"></td>
            </tr>
            <tr>
              <td>Owner</td>
              <td>
                <select name="owner">
                  <option selected="">none</option>
                  {% for owner_i in ownerList %}
                  <option value={{owner_i.username}}>{{owner_i.username}}</option>
                  {% endfor %}
                  </select>
              </td>
            </tr>
            <tr>
              <td>Description</td>
              <td><input type="text" name="description" value="{{todo_description}}"></td>
            </tr>
            <tr>
              <td>Creation Date</td>
              <td><input type="datetime-local" name="creationDate" value="{{todo_creation_date}}"></td>
            </tr>
            <tr>
              <td>Due Date</td>
              <td><input type="datetime-local" name="dueDate" value="{{todo_due_date}}"></td>
            </tr>
            <tr>
              <td>Status</td>
              <td><input type="text" name="status" value="{{todo_status}}"></td>
            </tr>
            <tr>
              <td>Tags</td>
              <td><input type="text" name="tags" value="{{todo_tags}}"></td>
            </tr>
          </table>
        </fieldset>
        <input type="submit" value="save">
      </form>
      {% if todo_id %}
      <form action="{% url 'djangoTask:delete' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="todo_id" value="{{todo_id}}">
        <input type="submit" value="delete">
      </form>
      {% endif %}
  </div>
  {% endblock %}
  {% block navActive %} "{{ navLink }}" {% endblock %}

templates/djangoTask/export.html
{% extends "djangoTask/base.html"  %}
{% block title %}export{% endblock %}
{% block navActive %}"export"{% endblock %}
{% block content %}
<div class="container-content">
  <div class="container-fluid">
    <h3>Export Todos:</h3>
  </div>
  <div class="container-fluid">
    <p>{{ export }}</p>
  </div>
{% endblock %}

templates/djangoTask/forbidden.html
{% extends "djangoTask/base.html"  %}
{% block title %}Forbidden{% endblock %}
{% block navActive %}"none"{% endblock %}
{% block content %}
<div class="container-content">
  <div class="container-fluid">
    <h1>Forbidden</h1>
  </div>

  <div class="container-fluid">
    <p>Insufficient priveleges to fulfill the request.  Please try again or contact the administrator.<p>
    {% if message %}
    {{ message }}
    {% endif %}
  </div>
</div>
{% endblock %}

templates/djangoTask/import.html
{% extends "djangoTask/base.html"  %}
{% block title %}import{% endblock %}
{% block navActive %}"import"{% endblock %}
{% block content %}
<div class="container-content">
  <div class="container-fluid">
    <p>{{ message }}</p>
  </div>

  <div class="container-fluid">
    <form action="{% url 'djangoTask:import' %}" method="post">
      {% csrf_token %}
      <fieldset>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <textarea name="inData" id="inData" value="{{ inData }}" rows="20" cols="100">{{ dataProvided }}</textarea>
      </fieldset>
      <input type="submit" value="save">
    </form>
    <p><i>Example:</i></p>
    <p>{{ example  }}</p>

  </div>

  {% endblock %}

templates/djangoTask/index.html
{% extends "djangoTask/base.html"  %}
{% block title %}Todo Index{% endblock %}
{% block navActive %}"index"{% endblock %}
{% block content %}
{% if latest_todo_list %}
<div class="container-content">
  {% if message %}
  <div class="container-fluid">
    <p>{{ message }}</p>
  </div>
  {% endif %}
  <table class="table table-striped table-hover table-sm">
    <thead>
      <tr>
        <th>id</th>
        <th>title</th>
        <th>owner</th>
        <th>status</th>
        <th>due date</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for todo in latest_todo_list %}
      <tr>
        <td>{{ todo.id}}</td>
        {% if todo.title %}
        <td><a href="{% url 'djangoTask:detail' todo.id %}">{{ todo.title }}</a></td>
        {% else %}
        <td><a href="{% url 'djangoTask:detail' todo.id %}">(no title)</a></td>
        {% endif %}
        <td>{{ todo.owner}}</td>
        <td>{{ todo.status}}</td>
        <td>{{ todo.due_date.date.isoformat }}</td>
        <td>
          <form action="{% url 'djangoTask:delete' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="todo_id" value="{{ todo.id }}">
            <input type="submit" value="delete">
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
<div class="container-content">
  <p>No todos are available.</p>
</div>
{% endif %}
{% endblock %}